services:
  frontend:
    image: ghcr.io/giovanivercauteren/crm-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    env_file:
      - frontend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm-frontend.rule=Host(`crm.vercauteren.io`)"
      - "traefik.http.routers.crm-frontend.entrypoints=websecure"
      - "traefik.http.routers.crm-frontend.tls=true"
      - "traefik.http.routers.crm-frontend.tls.certresolver=le"
    networks:
      - proxy
  backend:
    image: ghcr.io/giovanivercauteren/crm-backend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - backend/.env
    depends_on:
      - db
    networks:
      - internal
      - proxy
  db:
    image: ghcr.io/giovanivercauteren/crm-database:latest
    restart: unless-stopped
    shm_size: "256mb"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
    env_file:
      - database/.env
    volumes:
      - db_data:/var/lib/postgresql/
    command: >
      -c shared_buffers=512MB
      -c effective_cache_size=1536MB
      -c work_mem=16MB
    networks:
      - internal

networks:
  internal:
    driver: bridge
  proxy:
    external: true

volumes:
  db_data:
