name: CI Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push frontend image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-vars.outputs.image }}
      repo_name_lower: ${{ steps.set-vars.outputs.repo_name_lower }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set lowercase owner + repo
        id: set-vars
        run: |
          IMAGE_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')
          REPO_NAME_LOWER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/$IMAGE_OWNER/$REPO_NAME_LOWER"
          echo "IMAGE_OWNER=$IMAGE_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME_LOWER=$REPO_NAME_LOWER" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "repo_name_lower=$REPO_NAME_LOWER" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}-frontend:latest
            ${{ env.IMAGE }}-frontend:${{ github.sha }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}-backend:latest
            ${{ env.IMAGE }}-backend:${{ github.sha }}

      - name: Build and push database image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:database"
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}-database:latest
            ${{ env.IMAGE }}-database:${{ github.sha }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          # remove target directory before copying
          rm: true
          source: "docker-compose.yml"
          target: "/containers/${{ needs.build-and-push.outputs.repo_name_lower }}/"

      - name: Pull image and start
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /containers/${{ needs.build-and-push.outputs.repo_name_lower }}

            cat > .env <<EOL
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DB_URL=${{ secrets.DB_URL }}
            EOF

            chmod 600 .env

            docker compose pull
            docker compose up -d
